### ISSUE TITLE
Launch a Docker container and join Weave network

### ISSUE THREAD

**Issue by coffenbacher** [tutumcloud/weave-daemon#27]
Hi, 

I want to be able to launch containers that join Weave from outside of Tutum. I installed the tutum-agent for BYON, so weave-daemon is running and trying to connect the containers I start but it's failing. For example something like this, on my Tutum node:

     docker run -it busybox

Yields: 

```
2015/11/22 02:50:00 [CONTAINER ATTACH]: Inspecting Containers 6878841c590d2ae673fcb8de9f049139ccba5fae23f5aed9ee2853389c274e22
2015/11/22 02:50:00 [CONTAINER ATTACH]: Attaching container 6878841c590d2ae673fcb8de9f049139ccba5fae23f5aed9ee2853389c274e22
2015/11/22 02:50:00 6878841c590d2ae673fcb8de9f049139ccba5fae23f5aed9ee2853389c274e22: cannot find the IP address to add to weave
````

If I manually set TUTUM_IP_ADDRESS to something it doesn't seem to work either.

**Comment by fermayo** [comment]
This image only works with Tutum, which is the one that sets `TUTUM_IP_ADDRESS`. It's not supposed to work outside of Tutum. For that you will need to use weave's internal IPAM: http://weave.works/guides/
